server:
  port: 2267
  servlet:
    context-path: /text
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  type-aliases-package: com.h3c.entity
  mapper-locations: classpath:com/h3c/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

