server:
  port: 2267
  servlet:
    context-path: /text
    jsp:
      init-parameters:
        development:  true


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/h3c?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      suffix: .jsp


mybatis-plus:
  type-aliases-package: com.h3c.entity
  mapper-locations: classpath:com/h3c/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
